controllers:
  main:
    containers:
      main:
        command:
          - /app/.venv/bin/uvicorn
          - hotbot.main:app
          - --host
          - 0.0.0.0
          - --port
          - "8000"
        image:
          repository: ghcr.io/boundcorp/hotbot/release
        env:
          DATABASE_HOST: postgres-postgresql
          APP_ENV: production
        envFrom:
          - secretRef:
              name: hotbot-production-secrets

service:
  main:
    controller: main
    ports:
      http:
        port: 8000
      
ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: hotbot.wtf
        paths:
          - path: /
            pathType: Prefix
            service:
              name: hotbot
              port: 8000
    tls:
      - secretName: hotbot-tls
        hosts:
          - hotbot.wtf