controllers:
  main:
    replicas: 3
    strategy: RollingUpdate
    containers:
      main:
        command:
          - /app/infra/prod/start-uvicorn.sh
        image:
          repository: ghcr.io/boundcorp/hotbot/release
        env:
          DATABASE_HOST: postgres-postgresql
          APP_ENV: production
        envFrom:
          - secretRef:
              name: hotbot-production-secrets
        probes:
          liveness:
            enabled: true
            port: 8000
          readiness:
            enabled: true
            port: 8000
          startup:
            enabled: true
            port: 8000
service:
  main:
    controller: main
    ports:
      http:
        port: 8000
      
ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: hotbot.wtf
        paths:
          - path: /
            pathType: Prefix
            service:
              name: hotbot
              port: 8000
    tls:
      - secretName: hotbot-tls
        hosts:
          - hotbot.wtf