# Generated by Django 5.1.1 on 2024-09-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0007_account_analysis_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='moderation_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='embeds',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='reactions',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='replies',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
