# Generated by Django 5.1.1 on 2024-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farcaster", "0010_alter_cast_options_alter_accounttag_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cast",
            name="moderation_duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
