# Generated by Django 5.1.1 on 2024-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0011_cast_moderation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='embed_descriptions',
            field=models.JSONField(default=dict),
        ),
    ]
