# Generated by Django 5.1.1 on 2024-09-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0013_alter_accounttag_tag_alter_cast_embed_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='moderation_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
