# Generated by Django 5.1.1 on 2024-09-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farcaster", "0014_cast_moderation_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="moderation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
