# Generated by Django 5.1.1 on 2024-09-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0015_channel_moderation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='moderation_status',
            field=models.CharField(blank=True, choices=[('excluded', 'Excluded'), ('no_action', 'No Action'), ('curated', 'Curated')], max_length=255, null=True),
        ),
    ]
