# Generated by Django 5.1.1 on 2024-09-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0016_cast_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='action_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='accounttag',
            name='tag',
            field=models.CharField(choices=[('automated', 'Automated, a message that is clearly automated, such as a bot or AI'), ('user_giving_tips_with_content', 'User Giving Tips, post also contains original content'), ('user_giving_tips_without_content', 'User Giving Tips, no original content'), ('bot_tip_reply', 'Bot Tip Reply, automated reply to a tipping message, usually saying remaining balance'), ('original_content', 'Original Content, a real human message, it is on-topic and valid user content (as opposed to spam, nonsense, or tipping-without-content), its not just "haha" or "great point"'), ('spam', 'Spam, garbage, not a real message'), ('promotional', 'Promotional, a message that is clearly a promotion for a product or service'), ('off_topic', 'Off Topic - completely unrelated to channel topic, very low likelihood of being relevant discussion. If unsure, dont tag as off-topic.'), ('hate_speech', 'Hate Speech - explicit racism, sexism, homophobia, transphobia, etc'), ('sexually_explicit', 'Sexually Explicit')], max_length=255),
        ),
        migrations.AlterField(
            model_name='casttag',
            name='tag',
            field=models.CharField(choices=[('automated', 'Automated, a message that is clearly automated, such as a bot or AI'), ('user_giving_tips_with_content', 'User Giving Tips, post also contains original content'), ('user_giving_tips_without_content', 'User Giving Tips, no original content'), ('bot_tip_reply', 'Bot Tip Reply, automated reply to a tipping message, usually saying remaining balance'), ('original_content', 'Original Content, a real human message, it is on-topic and valid user content (as opposed to spam, nonsense, or tipping-without-content), its not just "haha" or "great point"'), ('spam', 'Spam, garbage, not a real message'), ('promotional', 'Promotional, a message that is clearly a promotion for a product or service'), ('off_topic', 'Off Topic - completely unrelated to channel topic, very low likelihood of being relevant discussion. If unsure, dont tag as off-topic.'), ('hate_speech', 'Hate Speech - explicit racism, sexism, homophobia, transphobia, etc'), ('sexually_explicit', 'Sexually Explicit')], max_length=255),
        ),
    ]
