# Generated by Django 5.1.1 on 2024-09-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farcaster', '0017_cast_action_log_alter_accounttag_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cast',
            name='last_refetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
