# Generated by Django 5.1.1 on 2024-09-06 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('openai_id', models.CharField(max_length=128, unique=True)),
                ('success', models.BooleanField(default=True)),
                ('content', models.JSONField()),
                ('refusal_reason', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=64)),
                ('completion_tokens', models.IntegerField()),
                ('prompt_tokens', models.IntegerField()),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
            },
        ),
    ]
