name: Deploy to Production

on:
  workflow_run:
    workflows: [build, test]
    types:
      - completed
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        chmod 600 kubeconfig
    - name: Deploy to production
      env:
        KUBECONFIG: ./kubeconfig
        CI_REGISTRY_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        CI_COMMIT_SHA: ${{ github.sha }}
      run: |
        ./bin/helm-deploy ${{ github.sha }} production